# Generated by Django 3.0.6 on 2020-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_auto_20160726_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.FileField(upload_to=''),
        ),
    ]
